-- 1-1번
CREATE USER joeun_exam IDENTIFIED BY 123456;

-- 1-2번
ALTER USER joeun_exam DEFAULT TABLESPACE users;

-- 1-3번
ALTER USER joeun_exam QUOTA UNLIMITED ON users;

-- 1-4번
GRANT connect, resource TO joeun_exam;

--1-5번
CREATE TABLE BOARD 
(
  BOARD_NO NUMBER NOT NULL 
, TITLE VARCHAR2(100 BYTE) NOT NULL 
, CONTENT VARCHAR2(2000 BYTE) 
, WRITER VARCHAR2(20 BYTE) NOT NULL 
, REG_DATE DATE NOT NULL 
, UPD_DATE DATE NOT NULL 
);


--1-6 번
CREATE SEQUENCE SEQ_BOARD
INCREMENT BY 1 
START WITH 1
MINVALUE 1
MAXVALUE 10000;

-- 1-7번

INSERT INTO board (BOARD_NO, TITLE, CONTENT, WRITER, REG_DATE, UPD_DATE)
VALUES('1', '제목01', '내용01', '김조은', TO_DATE('22/12/27', 'YY/MM/DD'), TO_DATE('22/12/27', 'YY/MM/DD'));

INSERT INTO board (BOARD_NO, TITLE, CONTENT, WRITER, REG_DATE, UPD_DATE)
VALUES('2', '제목02', '내용02', '김조은', TO_DATE('22/12/27', 'YY/MM/DD'), TO_DATE('22/12/27', 'YY/MM/DD'));

-- 1-8 번
UPDATE BOARD
   SET TITLE = '수정01',
   CONTENT = '수정01'
WHERE BOARD_NO = '1';

UPDATE BOARD
   SET TITLE = '수정02',
   CONTENT = '수정02'
WHERE BOARD_NO = '2';

-- 1-9번
SELECT *
FROM BOARD
WHERE WRITER LIKE '김%';

-- 1-10번
DELETE FROM BOARD
WHERE WRITER = '김조은';


